import Foundation

struct ExtraordinarioU006: Codable {
    var id: String
    var universidad: Universidad
    var ejercicioFiscal: Int
    var instrumento: String
    var estatusConvenio: String
    var instrumento2022: String
    var estatusConvenio2022: String
    var montoFederalProdep: Double
    var instrumentoProdep: String
    var estatusProdep: String
    var fechaProdep: String
    var montoFederalRecExt: Double
    var instrumentoRecExt: String
    var fechaExt: String
    var estatusRecRxt: String
    var montoRegresoClases: Double
    var instrumentoRegresoClases: String
    var estatusRegresoClases: String
    var montoInclusionEstancias: Double
    var instrumentoInclusionEstancias: String
    var estatusInclusionEstancias: String
    var instrumentoIncrementoSalarial: String
    var estatusIncrementoSalarial: String
    var informacionIncrementoSalarial: String
    var montoFederalIncrementoSalarial: Double
    var clcIncrementoSalarial: Double
    var deficit: Double
    var instrumentoDeficit: String
    var estatusDeficit: String
    var fechaFirmaConvenioRecursoOrdinario: String
    var instrumentoAnexoModificatorioU006: String
    var montoFederalAsignadoConvenioAnexoModificatorioU006: Double
    var montoEstatalAsignadoConvenioAnexoModificatorioU006: Double
    var montoPublicoAsignadoConvenioAnexoModificatorioU006: Double
    var estatusConvenioAnexoModificatorioU006: String
    var fechaFirmaConvenioAnexoModificatorioU006: String
    var observacionesAnexoModificatorioU006: String
    var instrumentoU040: String
    var estatusConvenioU040: String
    var fechaFirmaConvenioU040: String
    var montoAsignadoConvenioU040: Double
    var instrumentoPPS300Profexce: String
    var estatusConvenioPPS300Profexce: String
    var fechaFirmaConvenioPPS300Profexce: String
    var montoAsignadoConvenioPPS300Profexce: Double
    var montoMinistradoPPS300Profexce: Double
    var proyectosDictaminadosFavorablementePPS300Profexce: Int
    var instrumentoVertienteAU079: String
    var estatusConvenioVertienteAU079: String
    var fechaFirmaConvenioVertienteAU079: String
    var montoAsignadoProgramaVertienteAEstablecidoConvenioU079: Double
    var instrumentoVertienteBU079: String
    var estatusConvenioVertienteBU079: String
    var fechaFirmaConvenioVertienteBU079: String
    var montoAsignadoProgramaVertienteBEstablecidoConvenioU079: Double
    var fechaFirmaConvenioDeficitU006: String
    var montoEstatalDeficitU006: Double
    var montoPublicoDeficitU006: Double
    var montoEstatalIncSalU006: Double
    var montoPublicoIncSalU006: Double
    var fechaFirmaConvenioInclusionEstancias: String
    var fechaFirmaConvenioRegresoClases: String
}
