import Foundation

struct IndicadoresEntidad : Codable {
    var id: String
    var entidadFederativa: ValorEntidades
    var ejercicioFiscal: Int
    var cicloDatos: String
    var poblacion18A22HombreCobertura: Int
    var poblacion18A22MujerCobertura: Int
    var poblacion18A22TotalCobertura: Int
    var porcentajeCoberturaHombreCobertura: Double
    var porcentajeCoberturaMujerCobertura: Double
    var tasaBrutaCobertura: Double
    var poblacion18A22HombreCobertura2013: Int
    var poblacion18A22MujerCobertura2013: Int
    var poblacion18A22TotalCobertura2013: Int
    var tasaBrutaCobertura2013: Double
    var matriculaLicenciaturaNs: Int
    var totalMatriculaTsuLicenciaturaNs: Int
    var matriculaTsuLicenciaturaHombresNs: Int
    var matriculaTsuLicenciaturaMujeresNs: Int
    var matriculaEspecialidadNs: Int
    var matriculaMaestriaNs: Int
    var matriculaDoctoradoNs: Int
    var totalMatriculaPosgradoNs: Int
    var matriculaPosgradoHombresNs: Int
    var matriculaPosgradoMujeresNs: Int
    var totalEmsEgresadosPublicoParticularNms: Int
    var emsEgresadosPublicoNms: Int
    var emsEgresadosPublicoFederalNms: Int
    var emsEgresadosPublicoEstatalNms: Int
    var emsEgresadosPublicoAutonomoNms: Int
    var emsEgresadosParticularNms: Int
    var totalPrimerIngresoPublicoParticularNms: Int
    var primerIngresoPublicoTsuLicNms: Int
    var primerIngresoPaticularTsuLicNms: Int
    var totalIndiceAbsorcion: Double
    var numeroIesEstadoPublicasParticularesDies: Int
    var upeEstadoDies: Int
    var upeasEstadoDies: Int
    var uiEstadoDies: Int
    var matriculaEscolTsuLicPosDesMod: Int
    var matriculaNoEscolTsuLicPosDesMod: Int
    var matriculaMixtaTsuLicPosDesMod: Int
    var totalPtc: Int
    var conPerfilDeseableVigente: Int
    var conSniVigente: Int
    var matriculaDiscapacidadTsuLicPosDesDiscapacidad: Int
    var hombresDesDiscapacidad: Int
    var mujeresDesDiscapacidad: Int
    var matriculaHliTsuLicPosDesHli: Int
    var hombresDeshli: Int
    var mujeresDeshli: Int
    var educacionCmpe: Int
    var artesHumanidadesCmpe: Int
    var cienciasSocialesDerechoCmpe: Int
    var administracionNegociosCmpe: Int
    var cienciasNaturalesMatematicasStadisticaCmpe: Int
    var teconologiasInformacionComunicacionCmpe: Int
    var ingenieriaManufacturaConstruccionCmpe: Int
    var agronomiaVeterinariaCmpe: Int
    var cienciasSaludCmpe: Int
    var serviciosCmpe: Int
    var totalMatriculaAreasCmpe: Int
    var matriculaCalidadBc: Int
    var matriculaTotalBc: Int
    var matriculaEvaluableBc: Int
    var porcentajeCoberturaTotalCalidadBc: Double
    var porcentajeCoberturaEvaluableBc: Double
    var upeSubsistema: Int
    var upeasSubsistema: Int
    var uiSubsistema: Int
    var upfSubsistema: Int
    var utSubsistema: Int
    var upolSubsistema: Int
    var institutosTecnologicosSubsistema: Int
    var iesEntidadesFederativasSubsistema: Int
    var normalesSubsistema: Int
    var upnProvinciaSubsistema: Int
    var camSubsistema: Int
    var particularesSubsistema: Int
    var totalSubsistema: Int
}
